# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            Brandon Does a Coding Bootcamp
tagline:          'at Tech Elevator - Columbus, OH'
description:      "Brandon does a coding bootcamp at Tech Elevator. He blogs about it here. "
url:              https://beefan.github.io/
baseurl:          https://beefan.github.io/tech-elevator-blog

author:
  name:           'Brandon Fannin'
  url:            https://brandonfannin.com

paginate:         100

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/beefan/beefan.github.io
